
[tags]
caption = 6-SeldNet 50мс (23 апр)
description = SeldNet Для 4-х элементной решетки с дискретизацией 250кГц. 5 семплов по 50мс. Шаг stft 25мс.
class = SELDNet
type = localizer
kind = 6
order = 1

[files]
model = weights.pth
scaler = scaler.joblib

[params]
CMT_block = False
CMT_split = False
ChAtten_DCA = False
ChAtten_ULE = False
FreqAtten = False
LinearLayer = False
average = 'macro'
dataset = 'mic'
dropout_rate = 0.05
encoder = 'conv'
evaluate_distance = True
f_pool_size = [4, 4, 2]
feature_label_resolution = 2
feature_sequence_length = 10
fmax_doa_salsalite = 2000
fmax_spectra_salsalite = 5000
fmin_doa_salsalite = 50
fnn_size = 128
fs = 250000
hop_len_s = 0.025
label_hop_len_s = 0.05
label_sequence_length = 5
lad_doa_thresh = 20
lad_reldist_thresh = 1.0
lowpass_hz = 20000.0
max_audio_len_s = 5
mel_fmax_hz = 5000.0
mel_fmin_hz = 0.0
modality = 'audio'
model = 'seldnet'
multi_accdoa = True
n_mics = 4
nb_channels = 10
nb_cnn2d_filt = 64
nb_fnn_layers = 1
nb_heads = 8
nb_mel_bins = 256
nb_rnn_layers = 2
nb_self_attn_layers = 2
nb_transformer_layers = 2
ngcc_seld_task = '6'
no_dist = True
predict_tdoa = False
raw_chunks = False
relative_dist = True
rnn_size = 128
saved_chunks = False
segment_based_metrics = False
t_pool_size = [2, 1, 1]
thresh_unify = 15
unique_classes = 3
use_mfcc = False
use_ngcc = False
use_salsalite = False

classes_list = ["C1", "C2", "C3"]
target_class =  0


